on:
  youtube:
    channel_id:
      - UC5PYHgAzJ1wLEidB58SK6Xw
    playlist_id:
      - PLNvhiaSh0IpBH9sp2ozPwWFe5ZhQJKzAv
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.youtube.outputs.title}}
          description: ${{on.youtube.outputs.description}}
          link: ${{on.youtube.outputs.link}}
        run: |
          echo title: $title
          echo description: $description
          echo link: $link
